version: '3'
services:
  redis:
    container_name: redis
    image: redis
  node:
    restart: on-failure
    build:
      context: .
      dockerfile: ./.docker/node.dev.Dockerfile
    depends_on: 
      - redis
    environment:
      PORT: 8080
      REDIS_PORT: 6379
      REDISTOGO_URL: redis
      api_key: /iX5Fvkrvro-l9N8dtlLGpn47nvlRRtephJcn8ca1z
    ports:
        - 8080:8080